// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkjtgmuranfqjfawdflr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZranRnbXVyYW5mcWpmYXdkZmxyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NDUwMjcsImV4cCI6MjA2NTUyMTAyN30.N_FKWT5srhibInBoXNroygxV73DwxNnmX78mhylbq7k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);